export const SPORT_CATEGORIES = {
  ENDURANCE: 'Endurance',
  STRENGTH_POWER: 'Strength & Power',
  TEAM_SPORTS: 'Team Sports',
  COMBAT: 'Combat Sports',
  EXPLOSIVE: 'Explosive Power',
  RACQUET: 'Racquet Sports',
};

export const SPORTS = [
  // ENDURANCE SPORTS
  {
    id: 'marathon',
    name: 'Marathon Running',
    category: SPORT_CATEGORIES.ENDURANCE,
    icon: '🏃',
    macroRatio: { protein: 15, carbs: 65, fat: 20 },
    positions: null,
  },
  {
    id: 'cycling',
    name: 'Road Cycling',
    category: SPORT_CATEGORIES.ENDURANCE,
    icon: '🚴',
    macroRatio: { protein: 15, carbs: 60, fat: 25 },
    positions: null,
  },
  {
    id: 'triathlon',
    name: 'Triathlon',
    category: SPORT_CATEGORIES.ENDURANCE,
    icon: '🏊',
    macroRatio: { protein: 20, carbs: 60, fat: 20 },
    positions: null,
  },
  {
    id: 'swimming',
    name: 'Distance Swimming',
    category: SPORT_CATEGORIES.ENDURANCE,
    icon: '🏊‍♂️',
    macroRatio: { protein: 20, carbs: 55, fat: 25 },
    positions: null,
  },
  {
    id: 'cross_country',
    name: 'Cross Country',
    category: SPORT_CATEGORIES.ENDURANCE,
    icon: '🏃‍♀️',
    macroRatio: { protein: 18, carbs: 60, fat: 22 },
    positions: null,
  },

  // STRENGTH & POWER SPORTS
  {
    id: 'bodybuilding',
    name: 'Bodybuilding',
    category: SPORT_CATEGORIES.STRENGTH_POWER,
    icon: '💪',
    macroRatio: { protein: 35, carbs: 40, fat: 25 },
    positions: null,
  },
  {
    id: 'powerlifting',
    name: 'Powerlifting',
    category: SPORT_CATEGORIES.STRENGTH_POWER,
    icon: '🏋️‍♀️',
    macroRatio: { protein: 30, carbs: 45, fat: 25 },
    positions: null,
  },
  {
    id: 'olympic_weightlifting',
    name: 'Olympic Weightlifting',
    category: SPORT_CATEGORIES.STRENGTH_POWER,
    icon: '🏋️‍♂️',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: null,
  },
  {
    id: 'crossfit',
    name: 'CrossFit',
    category: SPORT_CATEGORIES.STRENGTH_POWER,
    icon: '🏃‍♂️',
    macroRatio: { protein: 30, carbs: 45, fat: 25 },
    positions: null,
  },

  // TEAM SPORTS
  {
    id: 'soccer',
    name: 'Soccer',
    category: SPORT_CATEGORIES.TEAM_SPORTS,
    icon: '⚽',
    macroRatio: { protein: 20, carbs: 55, fat: 25 },
    positions: ['Goalkeeper', 'Defender', 'Midfielder', 'Forward'],
  },
  {
    id: 'basketball',
    name: 'Basketball',
    category: SPORT_CATEGORIES.TEAM_SPORTS,
    icon: '🏀',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: ['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center'],
  },
  {
    id: 'american_football',
    name: 'American Football',
    category: SPORT_CATEGORIES.TEAM_SPORTS,
    icon: '🏈',
    macroRatio: { protein: 30, carbs: 45, fat: 25 },
    positions: ['Quarterback', 'Running Back', 'Wide Receiver', 'Linebacker', 'Offensive Line', 'Defensive Line'],
  },
  {
    id: 'volleyball',
    name: 'Volleyball',
    category: SPORT_CATEGORIES.TEAM_SPORTS,
    icon: '🏐',
    macroRatio: { protein: 20, carbs: 55, fat: 25 },
    positions: ['Setter', 'Outside Hitter', 'Middle Blocker', 'Libero'],
  },
  {
    id: 'rugby',
    name: 'Rugby',
    category: SPORT_CATEGORIES.TEAM_SPORTS,
    icon: '🏉',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: ['Forward', 'Back'],
  },

  // COMBAT SPORTS
  {
    id: 'boxing',
    name: 'Boxing',
    category: SPORT_CATEGORIES.COMBAT,
    icon: '🥊',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: null,
  },
  {
    id: 'mma',
    name: 'MMA',
    category: SPORT_CATEGORIES.COMBAT,
    icon: '🥋',
    macroRatio: { protein: 30, carbs: 45, fat: 25 },
    positions: null,
  },
  {
    id: 'wrestling',
    name: 'Wrestling',
    category: SPORT_CATEGORIES.COMBAT,
    icon: '🤼',
    macroRatio: { protein: 30, carbs: 45, fat: 25 },
    positions: null,
  },
  {
    id: 'judo',
    name: 'Judo',
    category: SPORT_CATEGORIES.COMBAT,
    icon: '🥋',
    macroRatio: { protein: 28, carbs: 47, fat: 25 },
    positions: null,
  },

  // EXPLOSIVE POWER
  {
    id: 'sprinting',
    name: 'Sprinting (100m/200m)',
    category: SPORT_CATEGORIES.EXPLOSIVE,
    icon: '🏃‍♂️',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: null,
  },
  {
    id: 'high_jump',
    name: 'High Jump',
    category: SPORT_CATEGORIES.EXPLOSIVE,
    icon: '🤸',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: null,
  },
  {
    id: 'long_jump',
    name: 'Long Jump',
    category: SPORT_CATEGORIES.EXPLOSIVE,
    icon: '🏃‍♀️',
    macroRatio: { protein: 25, carbs: 50, fat: 25 },
    positions: null,
  },

  // RACQUET SPORTS
// ==================== RACQUET SPORTS ====================
{
  id: 'tennis',
  name: 'Tennis',
  category: SPORT_CATEGORIES.RACQUET,
  icon: '🎾',
  macroRatio: { protein: 20, carbs: 55, fat: 25 },
  positions: null,
},
{
  id: 'badminton',
  name: 'Badminton',
  category: SPORT_CATEGORIES.RACQUET,
  icon: '🏸',
  macroRatio: { protein: 20, carbs: 55, fat: 25 },
  positions: null,
},
{
  id: 'squash',
  name: 'Squash',
  category: SPORT_CATEGORIES.RACQUET,
  icon: '🎾',
  macroRatio: { protein: 22, carbs: 53, fat: 25 },
  positions: null,
},
{
  id: 'table_tennis',
  name: 'Table Tennis',
  category: SPORT_CATEGORIES.RACQUET,
  icon: '🏓',
  macroRatio: { protein: 20, carbs: 55, fat: 25 },
  positions: null,
},
{
  id: 'pickleball',
  name: 'Pickleball',
  category: SPORT_CATEGORIES.RACQUET,
  icon: '🏓',
  macroRatio: { protein: 20, carbs: 55, fat: 25 },
  positions: null,
},
{
  id: 'racquetball',
  name: 'Racquetball',
  category: SPORT_CATEGORIES.RACQUET,
  icon: '🎾',
  macroRatio: { protein: 22, carbs: 53, fat: 25 },
  positions: null,
},
];

export const TRAINING_PHASES = [
  { id: 'offseason', name: 'Off-Season', description: 'Low intensity, recovery focus' },
  { id: 'preseason', name: 'Pre-Season', description: 'Building fitness' },
  { id: 'inseason', name: 'In-Season', description: 'Maintaining performance' },
  { id: 'competition', name: 'Competition', description: 'Peak performance' },
];